/**
 * Built-in background music tracks.
 * Place royalty-free MP3 files in /public/audio/ matching these filenames.
 * Source: no-copyright-music.com by Liborio Conti — free for commercial use, no attribution required.
 */
export const AUDIO_TRACKS = [
  {
    id: "dramatic-tension",
    name: "Suspenseful",
    file: "/audio/dramatic-tension.mp3",
    mood: "Suspense, thriller",
    genre: "Orchestral",
    bpm: 90,
    tags: ["suspense", "thriller", "dark", "cinematic"],
    description: "Building tension for high-stakes and thriller scenes",
  },
  {
    id: "emotional-piano",
    name: "Sad Piano",
    file: "/audio/emotional-piano.mp3",
    mood: "Romance, drama",
    genre: "Piano",
    bpm: 68,
    tags: ["romance", "sad", "emotional", "intimate"],
    description: "Delicate solo piano for heartfelt and romantic moments",
  },
  {
    id: "dark-ambient",
    name: "Dark Score",
    file: "/audio/dark-ambient.mp3",
    mood: "Horror, mystery",
    genre: "Cinematic",
    bpm: 60,
    tags: ["horror", "mystery", "eerie", "dark"],
    description: "Dark cinematic score for tense and mysterious scenes",
  },
  {
    id: "upbeat-pop",
    name: "Summer",
    file: "/audio/upbeat-pop.mp3",
    mood: "Comedy, slice of life",
    genre: "Upbeat",
    bpm: 120,
    tags: ["happy", "fun", "light", "summer", "comedy"],
    description: "Bright and cheerful for lighthearted everyday scenes",
  },
  {
    id: "epic-orchestral",
    name: "Epic Adventure",
    file: "/audio/epic-orchestral.mp3",
    mood: "Action, fantasy",
    genre: "Orchestral",
    bpm: 140,
    tags: ["epic", "action", "adventure", "heroic"],
    description: "Full orchestra for grand action and fantasy sequences",
  },
  {
    id: "soft-jazz",
    name: "Exploration",
    file: "/audio/soft-jazz.mp3",
    mood: "Discovery, mystery",
    genre: "Cinematic",
    bpm: 80,
    tags: ["discovery", "mystery", "cinematic", "curious"],
    description: "Atmospheric cinematic piece for discovery and mystery scenes",
  },
  {
    id: "acoustic-indie",
    name: "Acoustic Inspirational",
    file: "/audio/acoustic-indie.mp3",
    mood: "Coming of age, friendship",
    genre: "Acoustic",
    bpm: 95,
    tags: ["acoustic", "warm", "inspiring", "nostalgic"],
    description: "Warm acoustic for coming-of-age and friendship stories",
  },
  {
    id: "corporate-inspire",
    name: "Inspire",
    file: "/audio/corporate-inspire.mp3",
    mood: "Ambition, motivation",
    genre: "Cinematic",
    bpm: 110,
    tags: ["motivational", "inspiring", "uplifting", "success"],
    description: "Uplifting cinematic music for ambition and triumph moments",
  },
  {
    id: "lofi-chill",
    name: "By The Fire",
    file: "/audio/lofi-chill.mp3",
    mood: "Cozy, everyday life",
    genre: "Ambient",
    bpm: 70,
    tags: ["cozy", "relaxed", "ambient", "warm", "peaceful"],
    description: "Warm and cozy atmosphere for intimate everyday scenes",
  },
  {
    id: "cinematic-sorrow",
    name: "Sad Cinematic",
    file: "/audio/cinematic-sorrow.mp3",
    mood: "Grief, loss",
    genre: "Orchestral",
    bpm: 55,
    tags: ["sad", "grief", "loss", "emotional", "cinematic"],
    description: "Mournful orchestral score for tragedy and loss",
  },
  {
    id: "tense-electronic",
    name: "The Chase",
    file: "/audio/tense-electronic.mp3",
    mood: "Chase, action, tension",
    genre: "Orchestral",
    bpm: 130,
    tags: ["chase", "tense", "action", "fast", "thriller"],
    description: "High-energy chase music, seamlessly loopable for action scenes",
  },
  {
    id: "romantic-strings",
    name: "Fragile Beauty",
    file: "/audio/romantic-strings.mp3",
    mood: "Love, passion",
    genre: "Orchestral",
    bpm: 72,
    tags: ["romantic", "beautiful", "love", "delicate", "strings"],
    description: "Gentle and beautiful orchestral piece for romantic moments",
  },
  {
    id: "traditional-asian",
    name: "Africa",
    file: "/audio/traditional-asian.mp3",
    mood: "World, cultural, vibrant",
    genre: "World",
    bpm: 100,
    tags: ["world", "africa", "cultural", "rhythmic", "vibrant"],
    description: "Vibrant world music with rich cultural rhythms",
  },
  {
    id: "middle-eastern",
    name: "Rio Samba",
    file: "/audio/middle-eastern.mp3",
    mood: "Latin, festive, energetic",
    genre: "World",
    bpm: 120,
    tags: ["latin", "samba", "festive", "energetic", "world"],
    description: "Lively Latin samba rhythms for festive and energetic scenes",
  },
  {
    id: "action-rock",
    name: "Through The Storm",
    file: "/audio/action-rock.mp3",
    mood: "Epic, struggle, perseverance",
    genre: "Orchestral",
    bpm: 150,
    tags: ["epic", "struggle", "intense", "cinematic", "dramatic"],
    description: "Intense orchestral piece for scenes of struggle and perseverance",
  },
]

export function getTrackById(id) {
  return AUDIO_TRACKS.find((t) => t.id === id) || null
}
