/**
 * Pre-built series templates.
 * Each template pre-fills the entire series form + starter characters.
 */
export const SERIES_TEMPLATES = [
  {
    id: "crime_empire",
    name: "Crime Empire",
    emoji: "🗡️",
    description: "A ruthless rise through the criminal underworld",
    form: {
      title: "Crime Empire",
      theme: "betrayal_revenge",
      tone: "dark, intense, gritty",
      setting: "Urban crime districts, warehouses, luxury penthouses",
      premise: "A street-level fixer discovers their boss has been laundering cartel money. When they stumble on the truth, they must decide whether to run, submit — or take the empire for themselves.",
      languages: ["en", "tr"],
      globalStylePrompt: "high contrast, dark red and black palette, rain-slicked streets, neon reflections",
      visualStyle: "cinematic",
    },
    characters: [
      {
        name: "Marco Reyes",
        role: "protagonist",
        appearance: {
          basePrompt: "Late 30s Latino man, lean build, weathered face with a scar above his left eyebrow, short dark hair with grey temples",
          wardrobeDefault: "Worn leather jacket over a dark t-shirt, dark jeans",
          distinguishingFeatures: "Scar above left eyebrow, intense dark eyes",
        },
        personality: {
          traits: ["resourceful", "loyal", "ruthless when cornered"],
          speechPattern: "Speaks quietly and directly — never wastes words",
          backstory: "Grew up in poverty, worked his way up through street-level crime. Fiercely loyal to those who gave him a chance.",
          motivations: ["Protect his sister", "Build a life beyond violence"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Viktor Dragan",
        role: "antagonist",
        appearance: {
          basePrompt: "50s Eastern European man, heavy build, shaved head, cold grey eyes, immaculate grooming",
          wardrobeDefault: "Expensive tailored suit, no tie",
          distinguishingFeatures: "Gold signet ring, unnervingly still when angry",
        },
        personality: {
          traits: ["calculating", "patient", "utterly amoral"],
          speechPattern: "Speaks in measured, courteous tones — more frightening than shouting",
          backstory: "Former intelligence officer turned crime lord. Built his empire on silence and fear.",
          motivations: ["Total control", "Eliminate anyone who knows too much"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Lena Park",
        role: "supporting",
        appearance: {
          basePrompt: "Early 30s Korean-American woman, sharp features, dark eyes, straight black hair in a practical cut",
          wardrobeDefault: "Tailored blazer, dark slacks",
          distinguishingFeatures: "Always composed, rarely shows emotion",
        },
        personality: {
          traits: ["intelligent", "secretive", "pragmatic"],
          speechPattern: "Precise and economical — chooses every word carefully",
          backstory: "Financial analyst who discovered the money trail. Her loyalty is unclear — she has her own agenda.",
          motivations: ["Financial freedom", "Exposing Viktor's network"],
          relationships: {},
          arcProgression: [],
        },
      },
    ],
  },
  {
    id: "forbidden_love",
    name: "Forbidden Love",
    emoji: "💔",
    description: "Star-crossed lovers torn apart by family and duty",
    form: {
      title: "Forbidden Love",
      theme: "love_and_loss",
      tone: "emotional, bittersweet, passionate",
      setting: "Istanbul — historic neighborhoods, Bosphorus waterfront, grand family mansions",
      premise: "Two people from rival families fall deeply in love during a chance meeting. As their families push them apart and secrets surface, they must choose between love and loyalty.",
      languages: ["en", "tr"],
      globalStylePrompt: "warm golden tones, Bosphorus backgrounds, dreamy atmosphere",
      visualStyle: "watercolor",
    },
    characters: [
      {
        name: "Ayla Koç",
        role: "protagonist",
        appearance: {
          basePrompt: "Mid 20s Turkish woman, olive skin, dark wavy hair past her shoulders, expressive brown eyes",
          wardrobeDefault: "Elegant but understated — silk blouses, modest cuts",
          distinguishingFeatures: "A small crescent-moon pendant she never removes",
        },
        personality: {
          traits: ["empathetic", "stubborn", "quietly brave"],
          speechPattern: "Warm and thoughtful, pauses before speaking important truths",
          backstory: "Raised in a strict family with high expectations. Has always suppressed her own desires for family duty.",
          motivations: ["Be true to herself", "Protect the people she loves"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Kerem Arslan",
        role: "antagonist",
        appearance: {
          basePrompt: "Early 30s Turkish man, tall and broad-shouldered, angular face, dark hair, intense hazel eyes",
          wardrobeDefault: "Business-casual — open collar shirts, well-fitted trousers",
          distinguishingFeatures: "A quiet intensity — he watches everything",
        },
        personality: {
          traits: ["proud", "conflicted", "deeply loyal to family"],
          speechPattern: "Confident but guarded — becomes vulnerable only in private",
          backstory: "Groomed to lead the rival family's business empire. Fell for Ayla before he knew who she was.",
          motivations: ["Honor his family", "Follow his heart"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Nilufer Koç",
        role: "supporting",
        appearance: {
          basePrompt: "Late 50s Turkish woman, dignified bearing, silver-streaked dark hair, sharp intelligent eyes",
          wardrobeDefault: "Traditional yet refined — conservative colours, jewellery",
          distinguishingFeatures: "A single silver streak in her dark hair",
        },
        personality: {
          traits: ["commanding", "protective", "secretly sympathetic"],
          speechPattern: "Formal and commanding in public, softer behind closed doors",
          backstory: "Ayla's mother. She herself was forced into a loveless marriage and carries that wound.",
          motivations: ["Protect her family's honour", "Secretly wants more for her daughter"],
          relationships: {},
          arcProgression: [],
        },
      },
    ],
  },
  {
    id: "masked_truth",
    name: "The Masked Truth",
    emoji: "🎭",
    description: "Identities hidden, lives intertwined, truth explosive",
    form: {
      title: "The Masked Truth",
      theme: "hidden_identity",
      tone: "mysterious, tense, psychological",
      setting: "A high-end private intelligence firm, luxury apartments, encrypted underground networks",
      premise: "An analyst at an elite security firm realizes her boss is the anonymous whistleblower who destroyed her father's career. As she investigates, her own identity comes under threat.",
      languages: ["en", "tr"],
      globalStylePrompt: "cool blue-green palette, deep shadows, reflective surfaces, CCTV-style framing",
      visualStyle: "noir",
    },
    characters: [
      {
        name: "Selin Akar",
        role: "protagonist",
        appearance: {
          basePrompt: "Late 20s Turkish woman, sharp intelligent eyes, dark hair worn up for work, neutral professional appearance",
          wardrobeDefault: "Clean professional — blazers, neutral tones, nothing that stands out",
          distinguishingFeatures: "Almost too composed — she controls every expression",
        },
        personality: {
          traits: ["meticulous", "patient", "hiding a deep anger"],
          speechPattern: "Measured and professional at work; cutting and precise when pushed",
          backstory: "Her father was a diplomat destroyed by a leak ten years ago. She joined the firm to find who did it.",
          motivations: ["Uncover the truth about her father", "Trust no one until she must"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Adrian Voss",
        role: "antagonist",
        appearance: {
          basePrompt: "Mid 40s European man, silver-grey hair, lean build, impeccable posture, pale blue eyes",
          wardrobeDefault: "Bespoke suits, minimal accessories",
          distinguishingFeatures: "Unusually still — he never fidgets",
        },
        personality: {
          traits: ["brilliant", "morally ambiguous", "genuinely believes his methods are justified"],
          speechPattern: "Philosophical and deliberate — frames everything as a chess problem",
          backstory: "Intelligence veteran turned private operator. Exposed Selin's father to prevent a larger catastrophe — or so he believes.",
          motivations: ["Control the narrative", "Prevent another catastrophe"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Dara Osei",
        role: "supporting",
        appearance: {
          basePrompt: "Early 30s Ghanaian-British woman, natural hair, warm dark skin, quick perceptive eyes",
          wardrobeDefault: "Casual-professional, colourful accents",
          distinguishingFeatures: "Laughs easily — disarming in a tense environment",
        },
        personality: {
          traits: ["perceptive", "humorous", "fiercely ethical"],
          speechPattern: "Direct and warm, but can pivot to serious instantly",
          backstory: "Selin's only real friend in the firm. She suspects something is off but doesn't know what.",
          motivations: ["Do right by people", "Protect Selin"],
          relationships: {},
          arcProgression: [],
        },
      },
    ],
  },
  {
    id: "rise_to_power",
    name: "Rise to Power",
    emoji: "👑",
    description: "From nothing to everything — but power has a price",
    form: {
      title: "Rise to Power",
      theme: "rags_to_riches",
      tone: "inspiring, dramatic, morally complex",
      setting: "A major city — from modest neighbourhoods to skyscraper boardrooms and exclusive galas",
      premise: "A young entrepreneur bootstraps a startup from nothing and battles into the highest circles of power. Each step up costs her a piece of who she was.",
      languages: ["en", "tr"],
      globalStylePrompt: "golden-hour warmth transitioning to neon luxury, sharp contrast between old and new worlds",
      visualStyle: "cinematic",
    },
    characters: [
      {
        name: "Zara Yıldız",
        role: "protagonist",
        appearance: {
          basePrompt: "Late 20s Turkish woman, determined expression, dark hair with natural waves, striking dark eyes that miss nothing",
          wardrobeDefault: "Evolves throughout the series — starts in modest jeans and blazers, ends in sharp designer cuts",
          distinguishingFeatures: "A quiet fire in her eyes",
        },
        personality: {
          traits: ["driven", "charismatic", "willing to cross lines she once swore she wouldn't"],
          speechPattern: "Natural storyteller — can inspire a room; becomes colder as she rises",
          backstory: "Grew up in financial hardship, watched her family struggle. Swore she'd build something real.",
          motivations: ["Prove she belongs at the top", "Never be powerless again"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Emre Sağlam",
        role: "antagonist",
        appearance: {
          basePrompt: "Late 40s Turkish man, polished and athletic, perfectly groomed silver hair at the temples, confident dark eyes",
          wardrobeDefault: "Impeccably tailored — every detail signals power",
          distinguishingFeatures: "The smile that never quite reaches his eyes",
        },
        personality: {
          traits: ["charming", "ruthless", "threatened by genuine talent"],
          speechPattern: "Mentor-like and warm on the surface; devastating when he turns",
          backstory: "Self-made mogul who got there by destroying competitors. Sees Zara as both an asset and a threat.",
          motivations: ["Stay at the top", "Control the next generation of power"],
          relationships: {},
          arcProgression: [],
        },
      },
      {
        name: "Can Doğan",
        role: "supporting",
        appearance: {
          basePrompt: "Early 30s Turkish man, open honest face, lean build, warm brown eyes, slightly rumpled appearance",
          wardrobeDefault: "Casual — hoodies, jeans; uncomfortable in formal settings",
          distinguishingFeatures: "Genuinely warm smile — rare in the circles they now move in",
        },
        personality: {
          traits: ["idealistic", "steady", "the conscience of the group"],
          speechPattern: "Honest and sometimes blunt — no talent for flattery",
          backstory: "Zara's oldest friend and co-founder. Still believes in the original mission.",
          motivations: ["Build something ethical", "Not lose Zara to the machine"],
          relationships: {},
          arcProgression: [],
        },
      },
    ],
  },
]
